#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Extract the active monitor
MONITOR=$(xrandr | grep " connected" | head -n 1 | cut -d " " -f1)

# Extract the monitor resolution
RESOLUTION=$(xrandr | awk -v mon="$MONITOR" '$1==mon {getline; print $1; exit}')

# Set the referesh rate to 144
if [ -n "$MONITOR" ] && [ -n "$RESOLUTION" ]; then
  xrandr --output "$MONITOR" --mode "$RESOLUTION" --rate 144
fi

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Set wallpaper
feh --bg-fill ~/Pictures/wallpapers/pexels-elijahsad.jpg

# Start picom
pkill picom
picom &

# Start polybar
pkill polybar
~/.config/polybar/scripts/launch.sh

# Start notification
pkill dunst
dunst &
