general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/colorschemes/catppuccin-latte.toml"
  # "~/.config/alacritty/colorschemes/catppuccin-frappe.toml"
  # "~/.config/alacritty/colorschemes/catppuccin-macchiato.toml"
  "~/.config/alacritty/colorschemes/catppuccin-mocha.toml"
]

[env]

TERM = "xterm-256color"

[window]

opacity = 1

padding.x = 0
padding.y = 0

[font]

# normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
# normal = { family = "FiraCode Nerd Font Mono"}
# normal = { family = "0xProto Nerd Font", style = "Regular" }
# normal = { family = "Adwaita Mono", style = "Regular" }
# normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
# normal = { family = "ComicShannsMono Nerd Font Mono", style = "Regular" }
# normal = { family = "VictorMono Nerd Font Mono", style = "Regular" }
# normal = { family = "Hack Nerd Font Mono", style = "Regular" }

size = 14

[selection]

save_to_clipboard = true

[mouse]

hide_when_typing = true
